services:
  postgres:
    image: postgres:15.7-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - alguien-sabe-db:/var/lib/postgresql/data 
#Cambiar el nombre de  volume-db por el de tu volumen
volumes:
  alguien-sabe-db:
    driver: "local"